compile_pdf:
  image: aergus/latex
  tags:
    - docker
  script:
    - cd src/
    - latexmk -pdf TFM-SergioRosello.tex
    - biber TFM-SergioRosello.tex
    - latexmk -pdf TFM-SergioRosello.tex
  artifacts:
    paths:
      - $CI_PROJECT_DIR/src/TFM-SergioRosello.pdf
